
title: Alex O'Nions
logo: /Assets/Me.jpg
description: Game Programmer and 4th Year Computer Games Applications Development Student
baseurl: "/Portfolio"
url: "https://aoniex.github.io"



#show_dowloads: true
theme: jekyll-theme-minimal
markdown: kramdown 
