title: Alex O'Nions
logo: /Assets/Me.jpg
description: Game Programmer and 4th Year Computer Games Applications Development Student
baseurl: "/Portfolio"
url: "https://aoniex.github.io"

collections:
  pages:
    output: true

# Uncomment this if you want download links to show
# show_downloads: true

theme: jekyll-theme-minimal
markdown: kramdown
